# Generated by Django 5.1.3 on 2024-11-21 10:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryModels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.ImageField(upload_to='gallery/')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
