# Generated by Django 5.1.3 on 2024-11-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='img',
            field=models.ImageField(upload_to='about_photos/'),
        ),
    ]
